# Generated by Django 6.0.3 on 2026-04-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_initial'),
        ('students', '0002_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('archived', 'Архівований')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('archived', 'Архівована')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('scheduled', 'Заплановано'), ('completed', 'Проведено'), ('cancelled', 'Скасовано')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='branches.group', verbose_name='Група')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('lessons_count', models.PositiveIntegerField(verbose_name='Кількість занять')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Тривалість (днів)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='branches.branch', verbose_name='Гілка')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементи',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутній'), ('absent', 'Відсутній'), ('late', 'Запізнився')], default='present', max_length=10, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Студент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='branches.lesson', verbose_name='Заняття')),
            ],
            options={
                'verbose_name': 'Відвідування',
                'verbose_name_plural': 'Відвідування',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
