# Generated by Django 5.2.12 on 2026-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_subject_status_alter_branch_status_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(choices=[('Україна', 'Україна'), ('Польща', 'Польща')], default='Україна', max_length=100, verbose_name='Країна'),
            preserve_default=False,
        ),
    ]
