# Generated by Django
from django.db import migrations, models
import django.db.models.deletion

def migrate_countries(apps, schema_editor):
    Branch = apps.get_model('branches', 'Branch')
    Country = apps.get_model('branches', 'Country')
    for branch in Branch.objects.all():
        if branch.country:
            c, _ = Country.objects.get_or_create(name=branch.country)
            branch.country = c.id
            branch.save(update_fields=['country'])

class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
            ],
        ),
        migrations.RunPython(migrate_countries),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.country', verbose_name='Країна'),
        ),
    ]
