# Generated by Django 5.2.12 on 2026-05-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_country_alter_branch_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='country',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='groups', to='branches.subject', verbose_name='Предмети'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='branches.subject', verbose_name='Предмет'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
