# Generated by Django 6.0.3 on 2026-05-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_remove_branch_country_remove_group_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальна кількість учасників у групі (0 = без обмежень)', null=True, verbose_name='Макс. кількість студентів'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Нотатки'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.CharField(blank=True, help_text='Номер аудиторії або назва кімнати', max_length=50, verbose_name='Аудиторія/кімната'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Заплановано'), ('completed', 'Проведено'), ('cancelled', 'Скасовано')], db_index=True, default='scheduled', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='branches.branch', verbose_name='Гілка'),
        ),
    ]
