# Generated by Django 6.0.3 on 2026-05-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_group_max_students_lesson_notes_lesson_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_students',
        ),
    ]
