# Generated by Django 6.0.5 on 2026-05-26 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_remove_group_max_students'),
        ('students', '0003_student_notes_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Заплановано'), ('completed', 'Проведено'), ('cancelled', 'Скасовано')], default='scheduled', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['status'], name='idx_branch_status'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status'], name='idx_group_status'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date', 'start_time', 'end_time'], name='idx_lesson_schedule'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['date'], name='idx_lesson_date'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['start_time'], name='idx_lesson_start'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['end_time'], name='idx_lesson_end'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='idx_lesson_status'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status'], name='idx_subject_status'),
        ),
    ]
