# Generated by Django 6.0.3 on 2026-04-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('parent_name', models.CharField(blank=True, max_length=255, verbose_name='ПІБ батьків')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон батьків')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email батьків')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='branches.branch', verbose_name='Гілка')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
