# Generated by Django 6.0.3 on 2026-04-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('archived', 'Архівований')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
