# Generated by Django 6.0.3 on 2026-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Нотатки'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('archived', 'Архівований')], db_index=True, default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
