# Generated by Django 6.0.5 on 2026-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_add_indexes_and_constraints'),
        ('students', '0003_student_notes_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('archived', 'Архівований')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='idx_student_status'),
        ),
    ]
